site_name: 科研实习室
site_url: https://example.com/
site_author: Leshan Chen

copyright: 本站所有内容均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans">CC BY-NC-SA 4.0</a> 协议许可

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式

nav:
  - 首页: index.md
  - 导师列表:
    - 谢涛: 
      - 实验室简介: advisors/tao_xie/basic_info.md
      - 文献知识库: advisors/tao_xie/literature.md
      - 项目演练场: advisors/tao_xie/projects.md
    - 孔雨晴:
      - 实验室简介: advisors/yuqing_kong/basic_info.md
      - 文献知识库: advisors/yuqing_kong/literature.md
    - 施柏鑫:
      - 实验室简介: advisors/boxin_shi/basic_info.md
      - 文献知识库: advisors/boxin_shi/literature.md
    - 王亦洲:
      - 实验室简介: advisors/yizhou_wang/basic_info.md
      - 文献知识库: advisors/yizhou_wang/literature.md
  - 示例:
    - 实验室简介: example/basic_info.md
    - 文献知识库: example/literature.md
    - 项目演练场: example/projects.md