site_name: 科研实习室
site_url: https://example.com/
site_author: Leshan Chen

theme:
  name: material
  language: zh
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式

nav:
  - 首页: index.md
  - 导师列表:
    - 谢涛: 
      - 实验室简介: advisors/tao_xie/basic_info.md
      - 文献知识库: advisors/tao_xie/literature.md
      - 项目演练场: advisors/tao_xie/projects.md
    - 示例:
      - 实验室简介: example/basic_info.md
      - 文献知识库: example/literature.md
      - 项目演练场: example/projects.md